<?php
/**
 * @file
 * adds additional renderers to Hurricane
 */

/**
 * Implements hook_hurricane_renderers().
 */
function hurricane_renderers_hurricane_renderers() {
  return array(
    'hurricane' => array(
      'label' => t('Hurricane'),
      'file' => drupal_get_path('module', 'hurricane_renderers') . '/hurricane.js',
      'parameters' => array(
        'color' => array('label' => t('Color'), 'default' => '#3182c5'),
        'letter-spacing' => array('label' => t('Lines'), 'default' => 15),
        'line-height' => array('label' => t('Length'), 'default' => 60),
        'font-size' => array('label' => t('Thickness'), 'default' => 50),
        'text-indent' => array('label' => t('Corners'), 'default' => 100),
        'word-spacing' => array('label' => t('Speed'), 'default' => 20),
        'font-weight' => array('label' => t('Trail'), 'default' => 5),
      ),
    ),
    'twister' => array(
      'label' => t('Twister'),
      'file' => drupal_get_path('module', 'hurricane_renderers') . '/twister.js',
      'parameters' => array(
        'color' => array('label' => t('Active'), 'default' => '#3182c5'),
        'background-color' => array('label' => t('Inactive'), 'default' => '#CCC'),
        'word-spacing' => array('label' => t('Pulse'), 'default' => '25'),
        'letter-spacing' => array('label' => t('Rotate'), 'default' => '25'),
        'font-weight' => array('label' => t('Shape'), 'default' => '1'),
        'line-height' => array('label' => t('Speed'), 'default' => 50),
      ),
    ),
  );
}
